apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2clientcredentials
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
    - name: clientId
      value: "zeebe"
    - name: clientSecret
      value: "VmhhKtSBMx"
    - name: scopes
      value: "camunda-identity"
    - name: tokenURL
      value: "http://camunda-platform-keycloak.camunda-platform.svc.cluster.local/auth/realms/camunda-platform/protocol/openid-connect/token"
    - name: headerName
      value: "authorization"